from typing import Protocol, Any, List, Dict, Optional, Type
from .config import AgentConfig

class CentralConfigClient(Protocol):
    def get_agent_config(self, name: str) -> Optional[AgentConfig]: ...
    def upsert_agent_config(self, config: AgentConfig) -> None: ...

class LLM(Protocol):
    def invoke(self, messages: List[Dict[str, str]], tools: List[Any]) -> str: ...
    def invoke_structured(self, messages: List[Dict[str, str]], tools: List[Any], output_schema: Type[Any]) -> Any: ...
    def invoke_agent_loop(self, messages: List[Dict[str, str]], tools: List[Any], max_iterations: int, output_schema: Optional[Type[Any]] = None) -> Any: ...

class LLMFactory(Protocol):
    def create(self, model_name: str, temperature: float, max_tokens: Optional[int], llm_profile: Optional[str] = None) -> LLM: ...
