name: Bug Report
description: Report a bug in pico-agent
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce the issue.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: pico-agent version
      placeholder: "0.2.0"
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.11"
    validations:
      required: true
